name: debug
description: 'List all artifacts'
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{ github.repository }}
  filter:
    description: Regexp for filtering items that should be identified as reports
    required: true
    default: '^report-'
runs:
  using: 'node16'
  main: 'list.js'
