name: artifacts-download-by-regex
description: 'Download all artifacts by regex'
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{ github.repository }}
  regex:
    description: todo # TODO
    required: false
    default: "^playwright-report-.*$"
  path:
    description: download artifacts to this directory
    required: true
runs:
  using: 'node16'
  main: 'download.js'
