name: remove
description: 'Remove all artifacts from the deleted branch'
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{ github.repository }}
  branch:
    description: Short name of the branch triggered by the delete action
    required: false
    default: ${{ github.event.ref }}
runs:
  using: 'node16'
  main: 'remove.js'
