on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: try to use debug.js
        uses: ./actions/debug.yml # Uses an action in the root directory
