name: deploy GitHub Page

on: 
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_run:
    workflows: ["remove artifacts"]
    types: [completed]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#TODO: define github-pages as variable ?
      - name: make directory for build
        run: mkdir ./github-pages

      - name: download artifacts by regex
        uses: redmine24/download-artifacts-via-regex@dev
        with:
          regex: "^playwright-report-.*$"
          path: github-pages
          metadata: github-pages/a/b/../../d/e/d/f/e/d/c/artifacts.json

      - name: DEBUG
        run: find github-pages -ls

      - name: Generate index.html
        run: echo "<html><body><h1>`date`</h1><pre><code>`find github-pages -ls `</code></pre></body></html>" > ./github-pages/index.html

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./github-pages
          destination: ./deploy-data

#TODO: name gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./deploy-data


  # Deployment job
  deploy:
    environment:
      name: reports
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
