name: generate

on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  #contents: read
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: genereate report
        run: |
          ts=$(date +%H-%M-%S)
          mkdir -p reports/${ts}
          touch reports/${ts}/.skip
          git config user.name test
          git config user.email test@example.com
          git add .
          git commit -m "generated ${ts}"
          git push origin HEAD:gh-pages



