name: GitHub Pages 

on: [workflow_dispatch]

jobs: 
  name: publish
  runs-on: ubuntu-latest
  - steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3

    - name: Display structure of downloaded files
      run: find . -ls
