name: remove artifacts
run-name: Remove ${{ github.event.ref }} artifacts. Debug artifacts-${{ github.event.ref }}
on: 
  delete:

permissions:
  actions: write

# TODO event? 
concurrency: artifacts-${{ github.event.ref }}

jobs:
  remove_artifacts:
    runs-on: ubuntu-latest
    name: remove
    if: ${{ github.event.ref != 'refs/heads/main' && github.event.ref_type == 'branch' }}
    steps:
      - uses: actions/checkout@v3
      - name: remove all depricated artifacts
        uses: redmine24/delete-artifacts-via-regex@dev
        with:
          regex: "^playwright-report-.*$"
